### ISSUE TITLE
Torne o portfólio mais acessível

### ISSUE THREAD

**Issue by alexcmgit** [lpaulovt/lpaulovt.github.io#1]
**_Problema_**
O seu repositório não está mostrando a URL do seu portfólio na parte de "About" do repositório, desta forma dificulta o acesso ao seu portfólio, visto que a pessoa terá de digitar o link na URL ao invés de simplesmente clicar no link que estaria na aba de about do repositório.

**_Como solucionar?_**
Nas configurações do repositório, coloque o link do seu portfólio (https://lpaulovt.github.io/) como a URL do repositório e faça uma breve descrição, e nessa parte também inclua o link, por exemplo:

**_Exemplo_**
Exemplo de descrição: 
Este é meu portfólio profissional, e você pode me conhecer e ver meus projetos aqui: https://lpaulovt.github.io/

Na parte de URL não tem exemplo nem segredo, basta adicionar a URL do seu portfólio

**_Por que?_**
Dessa forma aumenta as chances das pessoas que visitarem seu repositório visitarem a URL do seu portófio

**_Finalização_**
Se não tiver entendido algo ou tiver alguma dúvida, é só responder essa issue ou me chamar no chat do linkedin

Espero que leve em consideração, obrigado por ler até aqui! =D

**Comment by lpaulovt** [comment]
Opa Laks, tudo bem? :)

Obrigado pelas informações e pelas dicas, na verdade já estava ciente
delas, o real motivo de não ter feito elas ainda é porque estou organizando
um Readme e um post para LinkedIn para oficializar de uma vez o meu
portfólio.

Mas, fique tranquilo, sempre que tiver alguma dica pode enviar uma mensagem
para mim. :D

Abraços,
Paulo Lopes

**Comment by alexcmgit** [comment]
Ah sim, tudo certo então. Te vi dando Star no repo, por isso tive a ideia de que já estaria pronto hahaha, engano meu, desculpe. 
Vou aguardar pelo post e pelo README bonitão xD

Parabéns pelo portfólio e obrigado pela rápida resposta.

**Comment by lpaulovt** [comment]
Sem problemas, dei star sem querer kkkkk. Obrigado pelo elogio. Tenha uma
boa tarde. :)

Abraços,
Paulo Lopes.
